name: RSI Discord Alert

on:
  schedule:
    - cron: '0 13 * * *'   # KST 22:00
    - cron: '10 13 * * *'  # KST 22:10
  workflow_dispatch:

jobs:
  rsi-alert:
    runs-on: ubuntu-latest

    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install yfinance requests

    - name: Run RSI script
      run: python finance.py
